name: homebrew list formulas

on:
  workflow_dispatch:

jobs:
  macos:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - macos-14
          - macos-15
      fail-fast: false
    steps:

      - name: List brew formulas with versions
        run: |
          echo "=== brew formulas"
          brew list --versions
          echo "=== lzo info"
          brew info lzo
          echo "=== lzo prefix"
          brew --prefix lzo
          ls -alh $(brew --prefix lzo)

