name: Build wheels for macOS

on:
  workflow_dispatch:

jobs:
  build-w64:
    runs-on: macos-12
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
        architecture: ["x64"]

        # NO NEED for arm64 - x64 generates universal binaries 
        # architecture: ["x64", "arm64"]
    name: ${{ matrix.python-version }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Run cmake
        working-directory: ./lzo-2.10
        run: |
          mkdir build
          cd build
          cmake ..
      - name: Build lzo static lib
        working-directory: ./lzo-2.10/build
        run: make
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}
      - name: Build wheel
        env:
          LZO_DIR: ./lzo-2.10
        run: |
          python -m pip install -U pip
          python -m pip install -U wheel
          python -m pip install -U setuptools
          python setup.py bdist_wheel
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-lzo-${{ matrix.python-version }}-macos-${{ matrix.architecture }}
          path: 'dist/**/*.whl'
          if-no-files-found: error
          
      - name: make release
        uses: ncipollo/release-action@v1
        with:
          name: python-lzo-${{ matrix.python-version }}-macos-${{ matrix.architecture }}
          body: macos-${{ matrix.architecture }}
          artifacts: "dist/**/*.whl"
          generateReleaseNotes: true
          tag: latest
